### ISSUE TITLE
library cannot stand alone

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-password-strength-checker#1]
This library assumes [RequireJS and jQuery are available](https://github.com/mozilla/fxa-password-strength-checker/blob/8e204254769d04ef35b3746cc5fe78ba0e470cbc/src/passwordcheck.js#L10), meaning that it cannot stand on its own.

Can we somehow get rid of at least the jQuery dependency and pass in a function that can be used for XHR calls?

The [fxa-js-client](https://github.com/mozilla/fxa-js-client/) has similar requirements (uses external libraries, uses RequireJS, needs to make XHR calls) and may be a good source of inspiration.

**Comment by TDA** [comment]
@shane-tomlinson do u want the xhr object to a parameter to the function? cause that would delay the loading of the bloomfilter_data until the function is called from the signup page. We need to have the ajax call done as soon as this module is loaded or we risk not having the file loaded.
