### ISSUE TITLE
bloomfilter.js needs license information

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-password-strength-checker#16]
[bloomfilter.js](https://github.com/mozilla/fxa-password-strength-checker/blob/master/src/bloomfilter.js) is open source code written by somebody else, it's licensing information and a link to the original source code should be included at the top of the file. We want to give credit where credit is due.

**Comment by pdehaan** [comment]
Just to confuse things, I'll say that we should include a MPL license file in this repo and probably include our boilerplate MPL header in each of the *.js files.
