### ISSUE TITLE
warning when running `grunt lint`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-password-strength-checker#19]
From https://github.com/mozilla/fxa-password-strength-checker/pull/12#discussion_r36041663

---

I see the following warning when running `grunt lint`:

``` bash
➜  fxa-password-strength-checker git:(issue-3-verbose) grunt lint
Running "eslint:app" (eslint) task

src/bloomdata_short_pwd.js
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override

✖ 1 problem (0 errors, 1 warning)
```

We generally treat warnings like errors - they shouldn't be there.

**Comment by pdehaan** [comment]
Looks like the easiest way to fix this is to just exclude it from eslint glob.

``` js
      src: [
        'Gruntfile.js',
        'tasks/*.js',
        'src/*.js',
        '!src/bloomdata_short_pwd.js'
      ]
```

**Comment by TDA** [comment]
Fixed in https://github.com/mozilla/fxa-password-strength-checker/pull/21
