### ISSUE TITLE
url to fetch data file is hard coded and will not work with alternative directory structures

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-password-strength-checker#2]
See [this line](https://github.com/mozilla/fxa-password-strength-checker/blob/8e204254769d04ef35b3746cc5fe78ba0e470cbc/src/passwordcheck.js#L18). This line assumes the data will be available one directory up, then in the bower_components/password-strength-checker directory.

The source root directory should be configurable.

**Comment by TDA** [comment]
@shane-tomlinson what do you suggest? move it out into a constant and use the constant instead?

**Comment by shane-tomlinson** [comment]
Data files are no longer loaded asynchronously. Closing.
