### ISSUE TITLE
BLOOMFILTER_TRIGGERED is not used

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-password-strength-checker#25]
I do not see [BLOOMFILTER_TRIGGERED](https://github.com/mozilla/fxa-password-strength-checker/blob/master/src/passwordcheck.js#L23) used anywhere. Is it needed?

**Comment by TDA** [comment]
@shane-tomlinson You told me to leave it in, in case we need to gather metrics for how frequently the bloom filter was triggered. do you want me to remove it?

**Comment by shane-tomlinson** [comment]
Already removed, closing
