### ISSUE TITLE
original bloomdata_short_pwd.js data not included

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-password-strength-checker#26]
The data and script to create https://github.com/mozilla/fxa-password-strength-checker/blob/master/src/bloomdata_short_pwd.js is not included anywhere. This is needed to allow others to verify our work and so we can update the blocked list.

**Comment by TDA** [comment]
@shane-tomlinson Would it be all right if this was a link to an external repo? Or should we create a new repo on 'mozilla/' ?

**Comment by shane-tomlinson** [comment]
@TDA - I can see this as a two step process.

At a minimum, include the dictionary and the script used to create bloomdata_short_pwd.js, in this repo.
Then, add a link to the external dictionary, plus the script used to create the abbreviated dictionary.
