### ISSUE TITLE
Add Travis badge to README

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-password-strength-checker#3]
... 'cause I'm curious if Travis is configured+running for this repo and if it's currently passing, because I'm cautiously "skeptical" (mainly since `npm test` should [exit with a `1` error code](https://github.com/mozilla/fxa-password-strength-checker/blob/0404a991803cfc35b781a2e83c13fb9f7a603bc7/package.json#L11)).

**Comment by TDA** [comment]
fixed in commit 0404a991
