### ISSUE TITLE
add check for strong passwords with a minimum no of unique letters

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-password-strength-checker#38]
From https://github.com/mozilla/fxa-content-server/pull/2810#issuecomment-131988093,
Add a way to check if the password has 'X' unique characters, and if that is beyond the minimum requirement, consider it to be a strong password.
### Example

```
abcdefghij1234
```

can be considered to be stronger than 

```
aaaaaaaaaaaa
```

Tagging @rfk

**Comment by rfk** [comment]
From @TDA in https://github.com/mozilla/fxa-content-server/pull/2810#issuecomment-131991410:

On second thought, our check already ensures that there is atleast a letter+(number or specialchar) or vice versa. Do we really need to check for unique characters? I agree that it will let through aaaa1111aaaa , but abcd1234efgh is not cryptographically stronger is it? they result in the same search space.

**Comment by rfk** [comment]
I think is different to the minium-requirements filter described above, the concern here is more with allowing through obviously-good passwords than blocking obviously-bad ones.

It may be that "at least 10 different chars (of any type)" is a better filter than "at least 12 chars long" to detect things that are definitely a strong password.  Or we could do them both.

**Comment by shane-tomlinson** [comment]
I'm going to close this until we have more metrics on how the password-strength meter is doing. If we still want this then, re-open.
